### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/modulo-3-evaluacion-intermedia-sandratapia#1]
Buen trabajo @sandratapia !

### Algunas pistas para acabarlo:

- [x] Usa el `id` de cada pokemon en el `li` para el `key` de react cuando mapeas y creas un listado de componentes
- [ ] Cuidado con anidad operadores ternarios, puede quedar muy ilegible https://github.com/Adalab/modulo-3-evaluacion-intermedia-sandratapia/blob/master/src/components/CardPokemon.js#L29

- Gracias por añadir las evoluciones y los cambios de color en función del tipo.

### Cuando tengas esto si quieres puedes:

1. Añadir un click a Pokemon que: marca o desmarca el pokemon como favorito en el array del estado de App.
1. Pasar este dato al componente Pokemon por props
1. Pintar Pokemon con otros estilos cuando por props nos llegue la info de que el pokemon es favorito

Si tienes cualquier duda, avisa!

Al turrón!!!

**Comment by sandratapia** [comment]
Hola Miguel,

Ya he cambiado los <li> para que cada uno tenga su key, y he añadido la funcionalidad de que se añadan como favoritos. 
Se que lo de anidar ternarios queda un poco mal, pero no encontré otra manera de hacerlo, habría alguna otra manera?

Gracias!
